# Generated by Django 4.1.3 on 2022-11-29 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('divition', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('birth', models.DateField()),
                ('adress', models.CharField(max_length=255)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='gestion.course')),
            ],
        ),
    ]
